<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="EntityFramework.ja" Version="6.2.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\BCartApi\BCartApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="\\172.18.88.15\Share\1共通\017.流通・サービス開発部\03_流通・サービスグループ\03_プロジェクト\97_丹波屋_システムアセスメント\999_SourceCode\BCart\Bat\BCartLinkBatch\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="\\172.18.88.15\Share\1共通\017.流通・サービス開発部\03_流通・サービスグループ\03_プロジェクト\97_丹波屋_システムアセスメント\999_SourceCode\BCart\Bat\BCartLinkBatch\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ApiSets\DataSet1.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DataSet1.xsd</DependentUpon>
    </Compile>
    <Compile Update="ApiSets\DataSet2.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DataSet2.xsd</DependentUpon>
    </Compile>
    <Compile Update="AppData\dsTnbToBcart.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>dsTnbToBcart.xsd</DependentUpon>
    </Compile>
    <Compile Update="Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="ApiSets\DataSet1.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DataSet1.Designer.cs</LastGenOutput>
    </None>
    <None Update="ApiSets\DataSet2.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DataSet2.Designer.cs</LastGenOutput>
    </None>
    <None Update="AppData\dsTnbToBcart.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsTnbToBcart.Designer.cs</LastGenOutput>
    </None>
    <None Update="Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
