//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bcart受注管理 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TKYSVTNB0509;Initial Catalog=tnb;Persist Security Info=True;User ID=t" +
            "nb;Password=tnb;Encrypt=False;TrustServerCertificate=True")]
        public string TnbDBConnectionString {
            get {
                return ((string)(this["TnbDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TKYSVTNB0509;Initial Catalog=ds1;Persist Security Info=True;User ID=t" +
            "nb;Password=tnb;Encrypt=False;TrustServerCertificate=True")]
        public string Ds1DBConnectionString {
            get {
                return ((string)(this["Ds1DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TKYSVTNB0509;Initial Catalog=tnbToBCart;Persist Security Info=True;Us" +
            "er ID=tnb;Password=tnb;Encrypt=False;TrustServerCertificate=True")]
        public string BCartDBConnectionString {
            get {
                return ((string)(this["BCartDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrinterDevice {
            get {
                return ((string)(this["PrinterDevice"]));
            }
            set {
                this["PrinterDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ListLimit {
            get {
                return ((int)(this["ListLimit"]));
            }
            set {
                this["ListLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogPath {
            get {
                return ((string)(this["LogPath"]));
            }
            set {
                this["LogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bcart")]
        public string BCartHttpClientName {
            get {
                return ((string)(this["BCartHttpClientName"]));
            }
            set {
                this["BCartHttpClientName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5IiwianRpIjoiZmUyZjY3MzMyNGQxNzM4" +
            "ZjYyZDk2ZmI5YmNlMmYwMzFkMThmMTMzY2JjNWU3MmRmMDA2OGRjODMzMzZjNjk3Y2UwYjQwZDY3YjM0" +
            "YzYyNmEiLCJpYXQiOjE3MDY2Nzg3NjMsIm5iZiI6MTcwNjY3ODc2MywiZXhwIjoxNzM4MzAxMTYzLCJz" +
            "dWIiOiI4ODQiLCJzY29wZXMiOlsidXNlci1yZWFkIiwicHJvZHVjdHMtcmVhZCIsInByb2R1Y3RzLXdy" +
            "aXRlIiwicHJvZHVjdF9jdXN0b21zLXJlYWQiLCJwcm9kdWN0X2N1c3RvbXMtd3JpdGUiLCJwcm9kdWN0" +
            "X3NldHMtcmVhZCIsInByb2R1Y3Rfc2V0cy13cml0ZSIsInByb2R1Y3Rfc2V0X29wdGlvbnMtcmVhZCIs" +
            "InByb2R1Y3Rfc2V0X29wdGlvbnMtd3JpdGUiLCJwcm9kdWN0X3NldF9jdXN0b21zLXJlYWQiLCJwcm9k" +
            "dWN0X3NldF9jdXN0b21zLXdyaXRlIiwicHJvZHVjdF9zdG9jay1yZWFkIiwicHJvZHVjdF9zdG9jay13" +
            "cml0ZSIsImNhdGVnb3JpZXMtd3JpdGUiLCJjYXRlZ29yaWVzLXJlYWQiLCJjdXN0b21lcnMtcmVhZCIs" +
            "ImN1c3RvbWVycy13cml0ZSIsImN1c3RvbWVyX2N1c3RvbXMtcmVhZCIsImN1c3RvbWVyX2N1c3RvbXMt" +
            "d3JpdGUiLCJvdGhlcl9hZGRyZXNzZXMtcmVhZCIsIm90aGVyX2FkZHJlc3Nlcy13cml0ZSIsIm9yZGVy" +
            "X3N0YXR1c2VzLXJlYWQiLCJvcmRlcl9zdGF0dXNlcy13cml0ZSIsIm9yZGVycy1yZWFkIiwib3JkZXJz" +
            "LXdyaXRlIiwib3JkZXJfcHJvZHVjdHMtcmVhZCIsIm9yZGVyX3Byb2R1Y3RzLXdyaXRlIiwib3JkZXJf" +
            "Y3VzdG9tcy1yZWFkIiwib3JkZXJfY3VzdG9tcy13cml0ZSIsImxvZ2lzdGljcy1yZWFkIiwibG9naXN0" +
            "aWNzLXdyaXRlIiwicHJpY2VfZ3JvdXBzLXJlYWQiLCJ2aWV3X2dyb3Vwcy1yZWFkIiwic2hpcHBpbmdf" +
            "Z3JvdXBzLXJlYWQiLCJwcm9kdWN0X2ZlYXR1cmVzLXJlYWQiLCJwcm9kdWN0X2ZlYXR1cmVzLXdyaXRl" +
            "IiwiYm9va21hcmtzLXJlYWQiLCJib29rbWFya3Mtd3JpdGUiLCJwb2ludHMtcmVhZCIsInBvaW50cy13" +
            "cml0ZSIsImVzdGltYXRlcy1yZWFkIiwiZXN0aW1hdGVfcHJvZHVjdHMtcmVhZCJdfQ.AsxaC3j5pTVqw" +
            "pTmnNSJNfTU-Se0QU2YMIoBvz33lkoj8m4p1RcJBFg4r6QqVIfrB1DZAx2M8AoR8AgAwWZKYM3lLYDzs" +
            "KYUHpYaD4pcZ8lo1ZtMjngJt_G-rQQnyQ6rhz_iSFsqYdv5XwZIXaj_OeCAr0JpGvZapjs7oE5G8XBfM" +
            "_lEz2JTi_16rR1XQwohP6ZZtCzNgYC6vtIQ8vXybcrDhSpUDx5beRWYDtFSnuN_Rp6qd7pEdBqTjrNw2" +
            "UPmr6QwtvCzX-rhlWSL4Kc6U7TeD-5r6eoXgmO-MVxr2jFNsRGi3caWY6X-a5d0GCtH7VMLHAuLPS8sS" +
            "Ru0dFN_xYk6dQasYS1n6mHUEkJKHIJ-WekSdCMkFYmEn7rEs2-_x7ZDlHivJvaqBchDGMm7Uk-PcJ8xD" +
            "vr_V84QgMFCh8-s7ya4NEyvEqgFwcWTpQ0xqPjDk6MZIZ9XoeMl0BBend_GI83IuEZcCDU2IkoqV6mlW" +
            "qvY_nhRoUk0xWgqbZm_FRVTDDeZPqZKx_NY0DsCaRVqpOiCQpKC0mLBfCEhRN7NRd2KN7o7xKdm4sa8K" +
            "eyfGDA0vLM3BWfUIZ6n_P7Z0-xdhcVRnl9aShJaXI-x0FWbfj9luCfNdONFb1SwUM_T2zYjxrDgkcSYl" +
            "QfrYVUWH1MQkQHBoNMfJT064wOt0_0")]
        public string BCartApiToken {
            get {
                return ((string)(this["BCartApiToken"]));
            }
            set {
                this["BCartApiToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.bcart.jp/api/v1/")]
        public string BCartApiBaseUrl {
            get {
                return ((string)(this["BCartApiBaseUrl"]));
            }
            set {
                this["BCartApiBaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegistTnb {
            get {
                return ((bool)(this["RegistTnb"]));
            }
            set {
                this["RegistTnb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrintPreview {
            get {
                return ((bool)(this["PrintPreview"]));
            }
            set {
                this["PrintPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.4.4")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public long Limit {
            get {
                return ((long)(this["Limit"]));
            }
            set {
                this["Limit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("360")]
        public int TimeoutInSeconds {
            get {
                return ((int)(this["TimeoutInSeconds"]));
            }
            set {
                this["TimeoutInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K:\\sagawa_本日出荷分.csv")]
        public string SagawaPath {
            get {
                return ((string)(this["SagawaPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\tkysvfs0502\\Share\\01_共有\\06_システム関連共有\\001_EC関連\\001_ピッキングリスト用商品画像")]
        public string ProductImagePath {
            get {
                return ((string)(this["ProductImagePath"]));
            }
        }
    }
}
